apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: csidrivers.csi.storage.k8s.io
  labels:
    {{- include "vault.labels" . | nindent 4}}
    app: {{ template "vault.fullname" . }}
spec:
  group: csi.storage.k8s.io
  names:
    kind: CSIDriver
    plural: csidrivers
  scope: Cluster
  version: v1alpha1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: csinodeinfos.csi.storage.k8s.io
  labels:
    {{- include "vault.labels" . | nindent 4}}
    app: {{ template "vault.fullname" . }}
spec:
  group: csi.storage.k8s.io
  names:
    kind: CSINodeInfo
    plural: csinodeinfos
  scope: Cluster
  version: v1alpha1
---
apiVersion: csi.storage.k8s.io/v1alpha1
kind: CSIDriver
metadata:
  name: {{ .Values.driverName }}
  labels:
    {{- include "vault.labels" . | nindent 4}}
    app: {{ template "vault.fullname" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  attachRequired: {{ .Values.attachRequired }}
  podInfoOnMountVersion: v1