apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "csi-vault.node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-vault.labels" . | nindent 4 }}
    component: {{ .Values.nodePlugin.name }}

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "csi-vault.node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-vault.labels" . | nindent 4 }}
    component: {{ .Values.nodePlugin.name }}
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "csi-vault.node.fullname" . }}
  labels:
    {{- include "csi-vault.labels" . | nindent 4 }}
    component: {{ .Values.nodePlugin.name }}
subjects:
- kind: ServiceAccount
  name: {{ template "csi-vault.node.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "csi-vault.node.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "csi-vault.node-registrar.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-vault.labels" . | nindent 4 }}
    component: {{ .Values.nodePlugin.name }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "update"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["storage.k8s.io"]
  resources: ["volumeattachments"]
  verbs: ["get", "list", "watch", "update", "create"]
- apiGroups: ["csi.storage.k8s.io"]
  resources: ["csidrivers", "csinodeinfos"]
  verbs: ["get", "watch", "list", "update", "patch", "create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list"]
- apiGroups: ["appcatalog.appscode.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["get", "create"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["get", "create"]
---

# needed for StatefulSet
kind: Service
apiVersion: v1
metadata:
  name: {{ template "csi-vault.node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-vault.labels" . | nindent 4 }}
    component: {{ .Values.nodePlugin.name }}
  {{- if and (eq .Values.monitoring.agent "prometheus.io/builtin") .Values.monitoring.node }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"
  {{- end }}
spec:
  selector:
    app: {{ template "csi-vault.name" . }}
    component: {{ .Values.nodePlugin.name }}
  ports:
  - name: api
    port: 443
    targetPort: 8443

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "csi-vault.node-registrar.fullname" . }}
  labels:
    {{- include "csi-vault.labels" . | nindent 4 }}
    component: {{ .Values.nodePlugin.name }}
subjects:
- kind: ServiceAccount
  name: {{ template "csi-vault.node.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "csi-vault.node-registrar.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

---

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ template "csi-vault.node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-vault.labels" . | nindent 4 }}
    component: {{ .Values.nodePlugin.name }}
spec:
  selector:
    matchLabels:
      app: {{ template "csi-vault.name" . }}
      component: {{ .Values.nodePlugin.name }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        {{- include "csi-vault.labels" . | nindent 8}}
        component: {{ .Values.nodePlugin.name }}
{{- if or .Values.annotations (and .Values.criticalAddon (eq .Release.Namespace "kube-system")) }}
      annotations:
{{- if and .Values.criticalAddon (eq .Release.Namespace "kube-system") }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
{{- end }}
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 8 }}
{{- end }}
{{- end }}
    spec:
      priorityClassName: system-node-critical
      serviceAccount: {{ template "csi-vault.node.fullname" . }}
            {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
            {{ toYaml .Values.imagePullSecrets | indent 6 }}
            {{- end }}
      containers:
      - name: node-driver-registrar
        image: {{ .Values.nodeRegistrar.registry}}/{{ .Values.nodeRegistrar.repository }}:{{ .Values.nodeRegistrar.tag }}
        args:
        - --v={{ .Values.logLevel }}
        - "--csi-address=$(ADDRESS)"
        - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: /var/lib/kubelet/plugins/{{ .Values.driverName }}/csi.sock
        - name: KUBE_NODE_NAME
              {{- include "csi-vault.node" . | nindent 10 }}
        imagePullPolicy: {{ .Values.nodeRegistrar.pullPolicy }}
        resources:
              {{ toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi/
        - name: registration-dir
          mountPath: /registration/
      - name: csi-vault-plugin
        image: {{ .Values.plugin.registry}}/{{ .Values.plugin.repository }}:{{ .Values.plugin.tag }}
        args :
        - run
        - "--endpoint=$(CSI_ENDPOINT)"
        - "--node=$(NODE_NAME)"
        - "--v={{ .Values.logLevel }}"
        - --secure-port=8443
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --use-kubeapiserver-fqdn-for-aks={{ .Values.apiserver.useKubeapiserverFqdnForAks }}
        - --enable-analytics={{ .Values.enableAnalytics }}
        ports:
        - containerPort: 8443
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: NODE_NAME
              {{- include "csi-vault.node" . | nindent 10 }}
        imagePullPolicy: {{ .Values.plugin.pullPolicy }}
              {{- if .Values.apiserver.healthcheck.enabled }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
              {{- end }}
        resources:
              {{ toYaml .Values.resources | indent 10 }}
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
        volumeMounts:
        - name: plugin-dir
          mountPath: /csi
        - name: pods-mount-dir
          mountPath: /var/lib/kubelet
                  # needed so that any mounts setup inside this container are
          # propagated back to the host machine.
          mountPropagation: "Bidirectional"
        - name: device-dir
          mountPath: /dev
        - mountPath: /var/serving-cert
          name: serving-cert
      volumes:
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: DirectoryOrCreate
      - name: plugin-dir
        hostPath:
          path: /var/lib/kubelet/plugins/{{ .Values.driverName }}
          type: DirectoryOrCreate
      - name: pods-mount-dir
        hostPath:
          path: /var/lib/kubelet
          type: Directory
      - name: device-dir
        hostPath:
          path: /dev
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ template "csi-vault.fullname" . }}-apiserver-cert
            {{- if or .Values.tolerations (and .Values.criticalAddon (eq .Release.Namespace "kube-system")) }}
      tolerations:
              {{- if .Values.tolerations }}
              {{ toYaml .Values.tolerations | indent 8 }}
              {{- end -}}
              {{- if and .Values.criticalAddon (eq .Release.Namespace "kube-system") }}
      - key: CriticalAddonsOnly
        operator: Exists
            {{- end -}}
            {{- end -}}
            {{- if .Values.affinity }}
      affinity:
            {{ toYaml .Values.affinity | indent 8 }}
            {{- end -}}
            {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | indent 8 }}
        {{- end -}}