# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/appscode/go"

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "0.3.0"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.11.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.6"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "~1.0.2"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.11.3"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
  name = "github.com/kubernetes-csi/csi-test"
  version = "v0.3.0-1"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "v1.0.0"

[[override]]
  name = "k8s.io/client-go"
  version = "v9.0.0"

[prune]
  go-tests = true
  unused-packages = true
