apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-attacher
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-attacher-runner
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "create"]
  - apiGroups: ["csi.storage.k8s.io"]
    resources: ["csidrivers", "csinodeinfos"]
    verbs: ["get", "watch", "list", "update", "patch", "create"]
  - apiGroups: ["appcatalog.appscode.com"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-role
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: csi-attacher
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: external-attacher-runner
  apiGroup: rbac.authorization.k8s.io
---
# needed for StatefulSet
kind: Service
apiVersion: v1
metadata:
  name: csi-attacher-vaultplugin
  namespace: {{ .Release.Namespace }}
  labels:
    app: csi-attacher-vaultplugin
spec:
  selector:
    app: csi-attacher-vaultplugin
  ports:
    - name: dummy
      port: 12345
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-attacher-vaultplugin
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: csi-attacher-vaultplugin
  serviceName: "csi-attacher-vaultplugin"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-attacher-vaultplugin
    spec:
      serviceAccount: csi-attacher
      containers:
        - name: csi-attacher
          image: {{ .Values.attacher.registry }}/{{ .Values.attacher.repository }}:{{ .Values.attacher.tag }}
          args:
            - "--v={{ .Values.logLevel }}"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: vault-csi-plugin
          image: {{ .Values.csi-vault.registry }}/{{ .Values.csi-vault.registry }}:{{ .Values.csi-vault.tag }}
          args :
            - init
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--node=$(NODE_NAME)"
            - "--v={{ .Values.logLevel }}"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}