apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-vault-provisioner
  namespace: ${VAULT_CSI_DRIVER_NAMESPACE}
  labels:
    app: vault-csi-driver
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vault-provisioner-role
  namespace: ${VAULT_CSI_DRIVER_NAMESPACE}
  labels:
    app: vault-csi-driver
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch"]
- apiGroups: ["csi.storage.k8s.io"]
  resources: ["csidrivers", "csinodeinfos"]
  verbs: ["get", "watch", "list", "update", "patch", "create"]
- apiGroups: ["appcatalog.appscode.com"]
  resources: ["*"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-vault-provisioner-binding
  namespace: ${VAULT_CSI_DRIVER_NAMESPACE}
  labels:
    app: vault-csi-driver
subjects:
- kind: ServiceAccount
  name: csi-vault-provisioner
  namespace: ${VAULT_CSI_DRIVER_NAMESPACE}
roleRef:
  kind: ClusterRole
  name: csi-vault-provisioner-role
  apiGroup: rbac.authorization.k8s.io
---
# needed for StatefulSet
kind: Service
apiVersion: v1
metadata:
  name: csi-vault-provisioner-service
  namespace: ${VAULT_CSI_DRIVER_NAMESPACE}
  labels:
    app: csi-vault-provisioner
spec:
  selector:
    app: csi-vault-provisioner
  ports:
  - name: dummy
    port: 12345
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-vault-provisioner
  namespace: ${VAULT_CSI_DRIVER_NAMESPACE}
  labels:
    app: csi-vault-provisioner
spec:
  selector:
    matchLabels:
      app: csi-vault-provisioner
  serviceName: csi-vault-provisioner-service
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-vault-provisioner
    spec:
      serviceAccount: csi-vault-provisioner
      containers:
      - name: csi-provisioner
        image: ${CSI_PROVISIONER_DOCKER_REGISTRY}/${CSI_PROVISIONER_DOCKER_REPOSITORY}:${CSI_PROVISIONER_IMAGE_TAG}
        args:
        - --provisioner=${VAULT_CSI_DRIVER_NAME}
        - "--csi-address=$(ADDRESS)"
        - "--v=5"
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        imagePullPolicy: ${CSI_ATTACHER_IMAGE_PULL_POLICY}
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/csi/sockets/pluginproxy/
      - name: vault-csi-plugin
        image: ${CSI_VAULT_DOCKER_REGISTRY}/${CSI_VAULT_DOCKER_REPOSITORY}:${CSI_VAULT_IMAGE_TAG}
        args :
        - init
        - "--endpoint=$(CSI_ENDPOINT)"
        - "--node=$(NODE_NAME)"
        - "--v=10"
        env:
        - name: CSI_ENDPOINT
          value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        imagePullPolicy: ${CSI_VAULT_IMAGE_PULL_POLICY}
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
      - name: socket-dir
        emptyDir: {}