apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: csidrivers.csi.storage.k8s.io
spec:
  group: csi.storage.k8s.io
  names:
    kind: CSIDriver
    plural: csidrivers
  scope: Cluster
  version: v1alpha1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: csinodeinfos.csi.storage.k8s.io
spec:
  group: csi.storage.k8s.io
  names:
    kind: CSINodeInfo
    plural: csinodeinfos
  scope: Cluster
  version: v1alpha1
---
apiVersion: csi.storage.k8s.io/v1alpha1
kind: CSIDriver
metadata:
  name: ${VAULT_CSI_DRIVER_NAME}
spec:
  attachRequired: ${CSI_REQUIRED_ATTACHMENT}
  podInfoOnMountVersion: v1