apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pki-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: vault-pki-storage
  volumeMode: DirectoryOrCreate


