apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: my-vault-volume
      mountPath: "/etc/foo"
      readOnly: true
  serviceAccountName: aws-vault
  volumes:
    - name: my-vault-volume
      persistentVolumeClaim:
        claimName: csi-aws-pvc




