apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vault-aws-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: com.vault.csi.vaultdbs
parameters:
  authRole: aws-cred-role
  secretEngine: AWS
  secretName: my-aws-role